repos:
- repo: local 
  hooks:
  - id: cargo-fmt
    name: cargo fmt
    language: system
    entry: cargo fmt --check
    files: \.rs$
    pass_filenames: false
  - id: markdownlint
    name: markdownlint
    language: node
    additional_dependencies: [markdownlint-cli]
    entry: markdownlint --config docs/config/.markdownlint.yml
    files: ^docs/.*\.md$
