# docker/Dockerfile.checks
FROM node:20-alpine

RUN apk add --no-cache ruby ruby-dev build-base && \
    gem install bundler

WORKDIR /app
COPY docs/local/Gemfile docs/local/_config.yml ./docs/local/
RUN bundle install --gemfile=docs/local/Gemfile

RUN npm install -g markdownlint-cli
