FROM node:20-alpine

RUN apk add --no-cache ruby ruby-dev build-base curl
RUN gem install bundler
WORKDIR /app
COPY docs/config/Gemfile docs/config/_config.yml ./docs/config/
RUN bundle install --gemfile=docs/config/Gemfile
