# docker/docker-compose-pre-commit.yml
services:
  checks:
    container_name: pre-commit 
    build:
      context: ..
      dockerfile: docker/Dockerfile
    working_dir: /app
    volumes:
      - ..:/app
    environment:
      BUNDLE_GEMFILE: /app/docs/config/Gemfile
