# docker/docker-compose-pre-commit.yml
services:
  checks:
    build:
      context: ..
      dockerfile: docker/Dockerfile.checks
    working_dir: /app
    volumes:
      - ..:/app
    environment:
      - BUNDLE_GEMFILE=/app/docs/ghp/Gemfile
      - SASS_CACHE_PATH=/tmp/sass-cache
